options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'extractor'
      - '--gen2'
      - '--runtime=python312'
      - '--region=europe-west1'
      - '--entry-point=main'
      - '--source=.'
      - '--trigger-topic=asteroid-workflow-topic'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--timeout=300s'
      - '--set-secrets'
      - 'NASA_KEY=projects/cloud-project-workflow/secrets/API_KEY/versions/latest'
